// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// EntBioUser is the predicate function for entbiouser builders.
type EntBioUser func(*sql.Selector)
