// Code generated by entc, DO NOT EDIT.

package ent

import (
	"back/ent/entbiouser"
	"back/ent/predicate"
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EntBioUserUpdate is the builder for updating EntBioUser entities.
type EntBioUserUpdate struct {
	config
	hooks    []Hook
	mutation *EntBioUserMutation
}

// Where appends a list predicates to the EntBioUserUpdate builder.
func (ebuu *EntBioUserUpdate) Where(ps ...predicate.EntBioUser) *EntBioUserUpdate {
	ebuu.mutation.Where(ps...)
	return ebuu
}

// SetName sets the "name" field.
func (ebuu *EntBioUserUpdate) SetName(s string) *EntBioUserUpdate {
	ebuu.mutation.SetName(s)
	return ebuu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (ebuu *EntBioUserUpdate) SetNillableName(s *string) *EntBioUserUpdate {
	if s != nil {
		ebuu.SetName(*s)
	}
	return ebuu
}

// Mutation returns the EntBioUserMutation object of the builder.
func (ebuu *EntBioUserUpdate) Mutation() *EntBioUserMutation {
	return ebuu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ebuu *EntBioUserUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ebuu.hooks) == 0 {
		affected, err = ebuu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EntBioUserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ebuu.mutation = mutation
			affected, err = ebuu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ebuu.hooks) - 1; i >= 0; i-- {
			if ebuu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ebuu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ebuu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (ebuu *EntBioUserUpdate) SaveX(ctx context.Context) int {
	affected, err := ebuu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ebuu *EntBioUserUpdate) Exec(ctx context.Context) error {
	_, err := ebuu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ebuu *EntBioUserUpdate) ExecX(ctx context.Context) {
	if err := ebuu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ebuu *EntBioUserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   entbiouser.Table,
			Columns: entbiouser.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: entbiouser.FieldID,
			},
		},
	}
	if ps := ebuu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ebuu.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: entbiouser.FieldName,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ebuu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entbiouser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// EntBioUserUpdateOne is the builder for updating a single EntBioUser entity.
type EntBioUserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EntBioUserMutation
}

// SetName sets the "name" field.
func (ebuuo *EntBioUserUpdateOne) SetName(s string) *EntBioUserUpdateOne {
	ebuuo.mutation.SetName(s)
	return ebuuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (ebuuo *EntBioUserUpdateOne) SetNillableName(s *string) *EntBioUserUpdateOne {
	if s != nil {
		ebuuo.SetName(*s)
	}
	return ebuuo
}

// Mutation returns the EntBioUserMutation object of the builder.
func (ebuuo *EntBioUserUpdateOne) Mutation() *EntBioUserMutation {
	return ebuuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ebuuo *EntBioUserUpdateOne) Select(field string, fields ...string) *EntBioUserUpdateOne {
	ebuuo.fields = append([]string{field}, fields...)
	return ebuuo
}

// Save executes the query and returns the updated EntBioUser entity.
func (ebuuo *EntBioUserUpdateOne) Save(ctx context.Context) (*EntBioUser, error) {
	var (
		err  error
		node *EntBioUser
	)
	if len(ebuuo.hooks) == 0 {
		node, err = ebuuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EntBioUserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ebuuo.mutation = mutation
			node, err = ebuuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ebuuo.hooks) - 1; i >= 0; i-- {
			if ebuuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ebuuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ebuuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (ebuuo *EntBioUserUpdateOne) SaveX(ctx context.Context) *EntBioUser {
	node, err := ebuuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ebuuo *EntBioUserUpdateOne) Exec(ctx context.Context) error {
	_, err := ebuuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ebuuo *EntBioUserUpdateOne) ExecX(ctx context.Context) {
	if err := ebuuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ebuuo *EntBioUserUpdateOne) sqlSave(ctx context.Context) (_node *EntBioUser, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   entbiouser.Table,
			Columns: entbiouser.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: entbiouser.FieldID,
			},
		},
	}
	id, ok := ebuuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing EntBioUser.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := ebuuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entbiouser.FieldID)
		for _, f := range fields {
			if !entbiouser.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != entbiouser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ebuuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ebuuo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: entbiouser.FieldName,
		})
	}
	_node = &EntBioUser{config: ebuuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ebuuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entbiouser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
