// Code generated by entc, DO NOT EDIT.

package ent

import (
	"back/ent/entbiouser"
	"back/ent/predicate"
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EntBioUserDelete is the builder for deleting a EntBioUser entity.
type EntBioUserDelete struct {
	config
	hooks    []Hook
	mutation *EntBioUserMutation
}

// Where appends a list predicates to the EntBioUserDelete builder.
func (ebud *EntBioUserDelete) Where(ps ...predicate.EntBioUser) *EntBioUserDelete {
	ebud.mutation.Where(ps...)
	return ebud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ebud *EntBioUserDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ebud.hooks) == 0 {
		affected, err = ebud.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EntBioUserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ebud.mutation = mutation
			affected, err = ebud.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ebud.hooks) - 1; i >= 0; i-- {
			if ebud.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ebud.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ebud.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ebud *EntBioUserDelete) ExecX(ctx context.Context) int {
	n, err := ebud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ebud *EntBioUserDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: entbiouser.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: entbiouser.FieldID,
			},
		},
	}
	if ps := ebud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ebud.driver, _spec)
}

// EntBioUserDeleteOne is the builder for deleting a single EntBioUser entity.
type EntBioUserDeleteOne struct {
	ebud *EntBioUserDelete
}

// Exec executes the deletion query.
func (ebudo *EntBioUserDeleteOne) Exec(ctx context.Context) error {
	n, err := ebudo.ebud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{entbiouser.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ebudo *EntBioUserDeleteOne) ExecX(ctx context.Context) {
	ebudo.ebud.ExecX(ctx)
}
