// Code generated by entc, DO NOT EDIT.

package ent

import (
	"back/ent/entbiouser"
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// EntBioUser is the model entity for the EntBioUser schema.
type EntBioUser struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EntBioUser) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case entbiouser.FieldID:
			values[i] = new(sql.NullInt64)
		case entbiouser.FieldName:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type EntBioUser", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EntBioUser fields.
func (ebu *EntBioUser) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case entbiouser.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ebu.ID = int(value.Int64)
		case entbiouser.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				ebu.Name = value.String
			}
		}
	}
	return nil
}

// Update returns a builder for updating this EntBioUser.
// Note that you need to call EntBioUser.Unwrap() before calling this method if this EntBioUser
// was returned from a transaction, and the transaction was committed or rolled back.
func (ebu *EntBioUser) Update() *EntBioUserUpdateOne {
	return (&EntBioUserClient{config: ebu.config}).UpdateOne(ebu)
}

// Unwrap unwraps the EntBioUser entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ebu *EntBioUser) Unwrap() *EntBioUser {
	tx, ok := ebu.config.driver.(*txDriver)
	if !ok {
		panic("ent: EntBioUser is not a transactional entity")
	}
	ebu.config.driver = tx.drv
	return ebu
}

// String implements the fmt.Stringer.
func (ebu *EntBioUser) String() string {
	var builder strings.Builder
	builder.WriteString("EntBioUser(")
	builder.WriteString(fmt.Sprintf("id=%v", ebu.ID))
	builder.WriteString(", name=")
	builder.WriteString(ebu.Name)
	builder.WriteByte(')')
	return builder.String()
}

// EntBioUsers is a parsable slice of EntBioUser.
type EntBioUsers []*EntBioUser

func (ebu EntBioUsers) config(cfg config) {
	for _i := range ebu {
		ebu[_i].config = cfg
	}
}
