// Code generated by entc, DO NOT EDIT.

package ent

import (
	"back/ent/entbiouser"
	"back/ent/predicate"
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EntBioUserQuery is the builder for querying EntBioUser entities.
type EntBioUserQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.EntBioUser
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EntBioUserQuery builder.
func (ebuq *EntBioUserQuery) Where(ps ...predicate.EntBioUser) *EntBioUserQuery {
	ebuq.predicates = append(ebuq.predicates, ps...)
	return ebuq
}

// Limit adds a limit step to the query.
func (ebuq *EntBioUserQuery) Limit(limit int) *EntBioUserQuery {
	ebuq.limit = &limit
	return ebuq
}

// Offset adds an offset step to the query.
func (ebuq *EntBioUserQuery) Offset(offset int) *EntBioUserQuery {
	ebuq.offset = &offset
	return ebuq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ebuq *EntBioUserQuery) Unique(unique bool) *EntBioUserQuery {
	ebuq.unique = &unique
	return ebuq
}

// Order adds an order step to the query.
func (ebuq *EntBioUserQuery) Order(o ...OrderFunc) *EntBioUserQuery {
	ebuq.order = append(ebuq.order, o...)
	return ebuq
}

// First returns the first EntBioUser entity from the query.
// Returns a *NotFoundError when no EntBioUser was found.
func (ebuq *EntBioUserQuery) First(ctx context.Context) (*EntBioUser, error) {
	nodes, err := ebuq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{entbiouser.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ebuq *EntBioUserQuery) FirstX(ctx context.Context) *EntBioUser {
	node, err := ebuq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EntBioUser ID from the query.
// Returns a *NotFoundError when no EntBioUser ID was found.
func (ebuq *EntBioUserQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ebuq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{entbiouser.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ebuq *EntBioUserQuery) FirstIDX(ctx context.Context) int {
	id, err := ebuq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EntBioUser entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one EntBioUser entity is not found.
// Returns a *NotFoundError when no EntBioUser entities are found.
func (ebuq *EntBioUserQuery) Only(ctx context.Context) (*EntBioUser, error) {
	nodes, err := ebuq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{entbiouser.Label}
	default:
		return nil, &NotSingularError{entbiouser.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ebuq *EntBioUserQuery) OnlyX(ctx context.Context) *EntBioUser {
	node, err := ebuq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EntBioUser ID in the query.
// Returns a *NotSingularError when exactly one EntBioUser ID is not found.
// Returns a *NotFoundError when no entities are found.
func (ebuq *EntBioUserQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ebuq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{entbiouser.Label}
	default:
		err = &NotSingularError{entbiouser.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ebuq *EntBioUserQuery) OnlyIDX(ctx context.Context) int {
	id, err := ebuq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EntBioUsers.
func (ebuq *EntBioUserQuery) All(ctx context.Context) ([]*EntBioUser, error) {
	if err := ebuq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ebuq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ebuq *EntBioUserQuery) AllX(ctx context.Context) []*EntBioUser {
	nodes, err := ebuq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EntBioUser IDs.
func (ebuq *EntBioUserQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := ebuq.Select(entbiouser.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ebuq *EntBioUserQuery) IDsX(ctx context.Context) []int {
	ids, err := ebuq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ebuq *EntBioUserQuery) Count(ctx context.Context) (int, error) {
	if err := ebuq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ebuq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ebuq *EntBioUserQuery) CountX(ctx context.Context) int {
	count, err := ebuq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ebuq *EntBioUserQuery) Exist(ctx context.Context) (bool, error) {
	if err := ebuq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ebuq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ebuq *EntBioUserQuery) ExistX(ctx context.Context) bool {
	exist, err := ebuq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EntBioUserQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ebuq *EntBioUserQuery) Clone() *EntBioUserQuery {
	if ebuq == nil {
		return nil
	}
	return &EntBioUserQuery{
		config:     ebuq.config,
		limit:      ebuq.limit,
		offset:     ebuq.offset,
		order:      append([]OrderFunc{}, ebuq.order...),
		predicates: append([]predicate.EntBioUser{}, ebuq.predicates...),
		// clone intermediate query.
		sql:  ebuq.sql.Clone(),
		path: ebuq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EntBioUser.Query().
//		GroupBy(entbiouser.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (ebuq *EntBioUserQuery) GroupBy(field string, fields ...string) *EntBioUserGroupBy {
	group := &EntBioUserGroupBy{config: ebuq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ebuq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ebuq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.EntBioUser.Query().
//		Select(entbiouser.FieldName).
//		Scan(ctx, &v)
//
func (ebuq *EntBioUserQuery) Select(fields ...string) *EntBioUserSelect {
	ebuq.fields = append(ebuq.fields, fields...)
	return &EntBioUserSelect{EntBioUserQuery: ebuq}
}

func (ebuq *EntBioUserQuery) prepareQuery(ctx context.Context) error {
	for _, f := range ebuq.fields {
		if !entbiouser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ebuq.path != nil {
		prev, err := ebuq.path(ctx)
		if err != nil {
			return err
		}
		ebuq.sql = prev
	}
	return nil
}

func (ebuq *EntBioUserQuery) sqlAll(ctx context.Context) ([]*EntBioUser, error) {
	var (
		nodes = []*EntBioUser{}
		_spec = ebuq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &EntBioUser{config: ebuq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, ebuq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ebuq *EntBioUserQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ebuq.querySpec()
	return sqlgraph.CountNodes(ctx, ebuq.driver, _spec)
}

func (ebuq *EntBioUserQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := ebuq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (ebuq *EntBioUserQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   entbiouser.Table,
			Columns: entbiouser.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: entbiouser.FieldID,
			},
		},
		From:   ebuq.sql,
		Unique: true,
	}
	if unique := ebuq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := ebuq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entbiouser.FieldID)
		for i := range fields {
			if fields[i] != entbiouser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ebuq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ebuq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ebuq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ebuq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ebuq *EntBioUserQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ebuq.driver.Dialect())
	t1 := builder.Table(entbiouser.Table)
	columns := ebuq.fields
	if len(columns) == 0 {
		columns = entbiouser.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ebuq.sql != nil {
		selector = ebuq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range ebuq.predicates {
		p(selector)
	}
	for _, p := range ebuq.order {
		p(selector)
	}
	if offset := ebuq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ebuq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EntBioUserGroupBy is the group-by builder for EntBioUser entities.
type EntBioUserGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ebugb *EntBioUserGroupBy) Aggregate(fns ...AggregateFunc) *EntBioUserGroupBy {
	ebugb.fns = append(ebugb.fns, fns...)
	return ebugb
}

// Scan applies the group-by query and scans the result into the given value.
func (ebugb *EntBioUserGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := ebugb.path(ctx)
	if err != nil {
		return err
	}
	ebugb.sql = query
	return ebugb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ebugb *EntBioUserGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := ebugb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (ebugb *EntBioUserGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(ebugb.fields) > 1 {
		return nil, errors.New("ent: EntBioUserGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := ebugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ebugb *EntBioUserGroupBy) StringsX(ctx context.Context) []string {
	v, err := ebugb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ebugb *EntBioUserGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ebugb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{entbiouser.Label}
	default:
		err = fmt.Errorf("ent: EntBioUserGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ebugb *EntBioUserGroupBy) StringX(ctx context.Context) string {
	v, err := ebugb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (ebugb *EntBioUserGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(ebugb.fields) > 1 {
		return nil, errors.New("ent: EntBioUserGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := ebugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ebugb *EntBioUserGroupBy) IntsX(ctx context.Context) []int {
	v, err := ebugb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ebugb *EntBioUserGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ebugb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{entbiouser.Label}
	default:
		err = fmt.Errorf("ent: EntBioUserGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ebugb *EntBioUserGroupBy) IntX(ctx context.Context) int {
	v, err := ebugb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (ebugb *EntBioUserGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(ebugb.fields) > 1 {
		return nil, errors.New("ent: EntBioUserGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := ebugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ebugb *EntBioUserGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := ebugb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ebugb *EntBioUserGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ebugb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{entbiouser.Label}
	default:
		err = fmt.Errorf("ent: EntBioUserGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ebugb *EntBioUserGroupBy) Float64X(ctx context.Context) float64 {
	v, err := ebugb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (ebugb *EntBioUserGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(ebugb.fields) > 1 {
		return nil, errors.New("ent: EntBioUserGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := ebugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ebugb *EntBioUserGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := ebugb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ebugb *EntBioUserGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ebugb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{entbiouser.Label}
	default:
		err = fmt.Errorf("ent: EntBioUserGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ebugb *EntBioUserGroupBy) BoolX(ctx context.Context) bool {
	v, err := ebugb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ebugb *EntBioUserGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range ebugb.fields {
		if !entbiouser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := ebugb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ebugb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ebugb *EntBioUserGroupBy) sqlQuery() *sql.Selector {
	selector := ebugb.sql.Select()
	aggregation := make([]string, 0, len(ebugb.fns))
	for _, fn := range ebugb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(ebugb.fields)+len(ebugb.fns))
		for _, f := range ebugb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(ebugb.fields...)...)
}

// EntBioUserSelect is the builder for selecting fields of EntBioUser entities.
type EntBioUserSelect struct {
	*EntBioUserQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ebus *EntBioUserSelect) Scan(ctx context.Context, v interface{}) error {
	if err := ebus.prepareQuery(ctx); err != nil {
		return err
	}
	ebus.sql = ebus.EntBioUserQuery.sqlQuery(ctx)
	return ebus.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ebus *EntBioUserSelect) ScanX(ctx context.Context, v interface{}) {
	if err := ebus.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (ebus *EntBioUserSelect) Strings(ctx context.Context) ([]string, error) {
	if len(ebus.fields) > 1 {
		return nil, errors.New("ent: EntBioUserSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := ebus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ebus *EntBioUserSelect) StringsX(ctx context.Context) []string {
	v, err := ebus.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (ebus *EntBioUserSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ebus.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{entbiouser.Label}
	default:
		err = fmt.Errorf("ent: EntBioUserSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ebus *EntBioUserSelect) StringX(ctx context.Context) string {
	v, err := ebus.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (ebus *EntBioUserSelect) Ints(ctx context.Context) ([]int, error) {
	if len(ebus.fields) > 1 {
		return nil, errors.New("ent: EntBioUserSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := ebus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ebus *EntBioUserSelect) IntsX(ctx context.Context) []int {
	v, err := ebus.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (ebus *EntBioUserSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ebus.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{entbiouser.Label}
	default:
		err = fmt.Errorf("ent: EntBioUserSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ebus *EntBioUserSelect) IntX(ctx context.Context) int {
	v, err := ebus.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (ebus *EntBioUserSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(ebus.fields) > 1 {
		return nil, errors.New("ent: EntBioUserSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := ebus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ebus *EntBioUserSelect) Float64sX(ctx context.Context) []float64 {
	v, err := ebus.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (ebus *EntBioUserSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ebus.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{entbiouser.Label}
	default:
		err = fmt.Errorf("ent: EntBioUserSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ebus *EntBioUserSelect) Float64X(ctx context.Context) float64 {
	v, err := ebus.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (ebus *EntBioUserSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(ebus.fields) > 1 {
		return nil, errors.New("ent: EntBioUserSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := ebus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ebus *EntBioUserSelect) BoolsX(ctx context.Context) []bool {
	v, err := ebus.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (ebus *EntBioUserSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ebus.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{entbiouser.Label}
	default:
		err = fmt.Errorf("ent: EntBioUserSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ebus *EntBioUserSelect) BoolX(ctx context.Context) bool {
	v, err := ebus.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ebus *EntBioUserSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ebus.sql.Query()
	if err := ebus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
