// Code generated by entc, DO NOT EDIT.

package ent

import (
	"back/ent/entbiouser"
	"back/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	entbiouserFields := schema.EntBioUser{}.Fields()
	_ = entbiouserFields
	// entbiouserDescName is the schema descriptor for name field.
	entbiouserDescName := entbiouserFields[0].Descriptor()
	// entbiouser.DefaultName holds the default value on creation for the name field.
	entbiouser.DefaultName = entbiouserDescName.Default.(string)
}
