// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// EntBioUsersColumns holds the columns for the "ent_bio_users" table.
	EntBioUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Default: "unknown"},
	}
	// EntBioUsersTable holds the schema information for the "ent_bio_users" table.
	EntBioUsersTable = &schema.Table{
		Name:       "ent_bio_users",
		Columns:    EntBioUsersColumns,
		PrimaryKey: []*schema.Column{EntBioUsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EntBioUsersTable,
	}
)

func init() {
}
